.TH "defs.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
defs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3.1415926535897932385"
.br
.ti -1c
.RI "#define \fBINFINITY\fP   1.0e40"
.br
.ti -1c
.RI "#define \fBsqr\fP(\fBx\fP)   ((\fBx\fP)*(\fBx\fP))"
.br
.ti -1c
.RI "#define \fBmin\fP(\fBx\fP, \fBy\fP)   ((\fBx\fP<\fBy\fP) ? \fBx\fP : \fBy\fP)"
.br
.ti -1c
.RI "#define \fBmax\fP(\fBx\fP, \fBy\fP)   ((\fBx\fP>\fBy\fP) ? \fBx\fP : \fBy\fP)"
.br
.ti -1c
.RI "#define \fBREAD_OPTIONAL_PARAMETER\fP(F)"
.br
.ti -1c
.RI "#define \fBREAD_PARAMETER_OR_DEFAULT\fP(F, D)"
.br
.ti -1c
.RI "#define \fBREAD_PARAMETER_OR_ERROR\fP(F)"
.br
.ti -1c
.RI "#define \fBforall\fP(\fBx\fP, S)   for (\fBx\fP = S.begin(); \fBx\fP != S.end(); \fBx\fP++)\\"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define forall(\fBx\fP, S)   for (\fBx\fP = S.begin(); \fBx\fP != S.end(); \fBx\fP++)\\"
.PP
.SS "#define INFINITY   1.0e40"
.PP
.SS "#define max(\fBx\fP, \fBy\fP)   ((\fBx\fP>\fBy\fP) ? \fBx\fP : \fBy\fP)"
.PP
.SS "#define min(\fBx\fP, \fBy\fP)   ((\fBx\fP<\fBy\fP) ? \fBx\fP : \fBy\fP)"
.PP
.SS "#define PI   3.1415926535897932385"
.PP
.SS "#define READ_OPTIONAL_PARAMETER(F)"
.PP
\fBValue:\fP
.PP
.nf
_msl_fin.clear();\
_msl_fin.open((FilePath+''#F'').c_str());\
if (_msl_fin) {_msl_fin >> F;}\
_msl_fin.close();\
.fi
.SS "#define READ_PARAMETER_OR_DEFAULT(F, D)"
.PP
\fBValue:\fP
.PP
.nf
_msl_fin.clear();\
_msl_fin.open((FilePath+''#F'').c_str());\
if (_msl_fin) {_msl_fin >> F;}\
else F = D;\
_msl_fin.close();\
.fi
.SS "#define READ_PARAMETER_OR_ERROR(F)"
.PP
\fBValue:\fP
.PP
.nf
_msl_fin.clear();\
_msl_fin.open((FilePath+''#F'').c_str());\
if (_msl_fin) {_msl_fin >> F; _msl_fin.close();}\
else {cerr << 'Error reading '#F'\n'; exit(-1);}\
_msl_fin.close();\
.fi
.SS "#define sqr(\fBx\fP)   ((\fBx\fP)*(\fBx\fP))"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
