.TH "fdp.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fdp.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fR
.br
\fC#include <stdio.h>\fR
.br
\fC#include "fdp.h"\fR
.br
\fC#include "defs.h"\fR
.br
\fC#include "marray.C"\fR
.br

.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.