.TH "FDPStar" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FDPStar \- An A-Star search variant. The Metric in \fBProblem\fP is used as the cost. 
.SH SYNOPSIS
.br
.PP
\fC#include <fdp.h>\fP
.PP
Inherits \fBFDP\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBFDPStar\fP (\fBProblem\fP *p)"
.br
.in -1c
.SS "Protected Methods"

.in +1c
.ti -1c
.RI "virtual double \fBSearchCost\fP (double initcost, \fBMSLNode\fP *&n, \fBMSLNode\fP *&nn)"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
An A-Star search variant. The Metric in \fBProblem\fP is used as the cost.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "FDPStar::FDPStar (\fBProblem\fP * p)"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "double FDPStar::SearchCost (double initcost, \fBMSLNode\fP *& n, \fBMSLNode\fP *& nn)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBFDP\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
