.TH "geomPQP.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geomPQP.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list.h>\fR
.br
\fC#include <vector.h>\fR
.br
\fC#include <PQP/PQP.h>\fR
.br
\fC#include <stdlib.h>\fR
.br
\fC#include <stdio.h>\fR
.br
\fC#include <string.h>\fR
.br
\fC#include "geom.h"\fR
.br
\fC#include "point.h"\fR
.br
\fC#include "triangle.h"\fR
.br
\fC#include "util.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBGeomPQP\fR"
.br
.RI "\fIParent class PQP-based list of Triangle models.\fR"
.ti -1c
.RI "class \fBGeomPQP2D\fR"
.br
.RI "\fIA parent class for 2D PQP geometries.\fR"
.ti -1c
.RI "class \fBGeomPQP2DRigid\fR"
.br
.RI "\fI2D rigid body.\fR"
.ti -1c
.RI "class \fBGeomPQP2DRigidMulti\fR"
.br
.RI "\fIA collection of 2D rigid bodies.\fR"
.ti -1c
.RI "class \fBGeomPQP3DRigid\fR"
.br
.RI "\fI3D rigid body.\fR"
.ti -1c
.RI "class \fBGeomPQP3DRigidMulti\fR"
.br
.RI "\fIA collection of 3D rigid modies.\fR"
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBMAXBODIES\fR  100"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define MAXBODIES  100
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.