.TH "geom.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geom.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list.h>\fR
.br
\fC#include <string>\fR
.br
\fC#include "vector.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBGeom\fR"
.br
.RI "\fIGeometric models and collision detection methods.\fR"
.ti -1c
.RI "class \fBGeomNone\fR"
.br
.RI "\fIA class with no geometry -- a collision never happens.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.