.TH "geomPQP.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geomPQP.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'MSL/geomPQP.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, PQP_Model &p)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const PQP_Model &p)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & os, const PQP_Model & p)"
.PP
.SS "istream& operator>> (istream & is, PQP_Model & p)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
