.TH "gui.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "problem.h"\fR
.br
\fC#include "scene.h"\fR
.br
\fC#include "render.h"\fR
.br
\fC#include <fx.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBGui\fR"
.br
.RI "\fIA generic class for designing graphical user interfaces (GUIs).\fR"
.in -1c
.SS Enumerations

.in +1c
.ti -1c
.RI "enum { \fBGID_RENDER_FIRST\fR =  FXMainWindow::ID_LAST, \fBGID_TOGGLE_SHOWPATH\fR, \fBGID_TOGGLE_BOUNDINGBOX\fR, \fBGID_TOGGLE_MULTIPLEVIEWS\fR, \fBGID_TOGGLE_ATTACHEDCAMERA\fR, \fBGID_VCR_STOP\fR, \fBGID_VCR_LAST\fR, \fBGID_VCR_PAUSE\fR, \fBGID_VCR_NEXT\fR, \fBGID_VCR_SLOWER\fR, \fBGID_VCR_PLAY\fR, \fBGID_VCR_FASTER\fR, \fBGID_VCR_RESET\fR, \fBGID_RENDER_LAST\fR, \fBGID_CONSTRUCT\fR, \fBGID_PLAN\fR, \fBGID_CLEAR_GRAPHS\fR, \fBGID_2D_GRAPH\fR, \fBGID_SAVE_GRAPHS\fR, \fBGID_LOAD_GRAPHS\fR, \fBGID_SAVE_FRAMES\fR, \fBGID_LOAD_FRAMES\fR, \fBGID_SAVE_PATH\fR, \fBGID_LOAD_PATH\fR, \fBGID_DONE\fR, \fBGID_RRT\fR, \fBGID_RRTGOALBIAS\fR, \fBGID_RRTCON\fR, \fBGID_RRTDUAL\fR, \fBGID_RRTEXTEXT\fR, \fBGID_RRTEXTCON\fR, \fBGID_RRTCONCON\fR, \fBGID_PRM\fR, \fBGID_FDP\fR, \fBGID_FDPSTAR\fR, \fBGID_FDPBESTFIRST\fR, \fBGID_FDPBI\fR, \fBGID_LAST\fR }"
.br
.in -1c
.SH ENUMERATION TYPE DOCUMENTATION
.PP 
.SS anonymous enum
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIGID_RENDER_FIRST\fR \fR
.TP
\fB\fIGID_TOGGLE_SHOWPATH\fR \fR
.TP
\fB\fIGID_TOGGLE_BOUNDINGBOX\fR \fR
.TP
\fB\fIGID_TOGGLE_MULTIPLEVIEWS\fR \fR
.TP
\fB\fIGID_TOGGLE_ATTACHEDCAMERA\fR \fR
.TP
\fB\fIGID_VCR_STOP\fR \fR
.TP
\fB\fIGID_VCR_LAST\fR \fR
.TP
\fB\fIGID_VCR_PAUSE\fR \fR
.TP
\fB\fIGID_VCR_NEXT\fR \fR
.TP
\fB\fIGID_VCR_SLOWER\fR \fR
.TP
\fB\fIGID_VCR_PLAY\fR \fR
.TP
\fB\fIGID_VCR_FASTER\fR \fR
.TP
\fB\fIGID_VCR_RESET\fR \fR
.TP
\fB\fIGID_RENDER_LAST\fR \fR
.TP
\fB\fIGID_CONSTRUCT\fR \fR
.TP
\fB\fIGID_PLAN\fR \fR
.TP
\fB\fIGID_CLEAR_GRAPHS\fR \fR
.TP
\fB\fIGID_2D_GRAPH\fR \fR
.TP
\fB\fIGID_SAVE_GRAPHS\fR \fR
.TP
\fB\fIGID_LOAD_GRAPHS\fR \fR
.TP
\fB\fIGID_SAVE_FRAMES\fR \fR
.TP
\fB\fIGID_LOAD_FRAMES\fR \fR
.TP
\fB\fIGID_SAVE_PATH\fR \fR
.TP
\fB\fIGID_LOAD_PATH\fR \fR
.TP
\fB\fIGID_DONE\fR \fR
.TP
\fB\fIGID_RRT\fR \fR
.TP
\fB\fIGID_RRTGOALBIAS\fR \fR
.TP
\fB\fIGID_RRTCON\fR \fR
.TP
\fB\fIGID_RRTDUAL\fR \fR
.TP
\fB\fIGID_RRTEXTEXT\fR \fR
.TP
\fB\fIGID_RRTEXTCON\fR \fR
.TP
\fB\fIGID_RRTCONCON\fR \fR
.TP
\fB\fIGID_PRM\fR \fR
.TP
\fB\fIGID_FDP\fR \fR
.TP
\fB\fIGID_FDPSTAR\fR \fR
.TP
\fB\fIGID_FDPBESTFIRST\fR \fR
.TP
\fB\fIGID_FDPBI\fR \fR
.TP
\fB\fIGID_LAST\fR \fR

.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.