.TH "guiplanner.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiplanner.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MSL/guiplanner.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFXDEFMAP\fP (\fBMSLPlannerWindow\fP) MSLPlannerWindowMap[]="
.br
.ti -1c
.RI "\fBFXIMPLEMENT\fP (\fBMSLPlannerWindow\fP, FXMainWindow, MSLPlannerWindowMap, ARRAYNUMBER(MSLPlannerWindowMap)) \fBMSLPlannerWindow\fP"
.br
.ti -1c
.RI "\fBFXIMPLEMENT\fP (\fBMSLPlotWindow\fP, FXDialogBox, MSLPlotWindowMap, ARRAYNUMBER(MSLPlotWindowMap)) \fBMSLPlotWindow\fP"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "FXDEFMAP (\fBMSLPlannerWindow\fP)"
.PP
.SS "FXIMPLEMENT (\fBMSLPlotWindow\fP, FXDialogBox, MSLPlotWindowMap, ARRAYNUMBER(MSLPlotWindowMap))"
.PP
.SS "FXIMPLEMENT (\fBMSLPlannerWindow\fP, FXMainWindow, MSLPlannerWindowMap, ARRAYNUMBER(MSLPlannerWindowMap))"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
