.TH "marray.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
marray.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBMultiArray\fR"
.br
.RI "\fIA multidimensional array made from a 1D vector.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.