.TH "marray.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
marray.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMultiArray\fP"
.br
.RI "\fIA multidimensional array made from a 1D vector.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
