.TH "matrix.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vector.h'\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLMatrix\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &O, const \fBMSLMatrix\fP &M)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &I, \fBMSLMatrix\fP &M)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & O, const \fBMSLMatrix\fP & M)"
.PP
.SS "istream& operator>> (istream & I, \fBMSLMatrix\fP & M)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
