.TH "matrix.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MSL/matrix.h'\fP
.br
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEPSILON\fP   1e-12"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBMSLMatrix\fP &M)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBMSLMatrix\fP &M)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define EPSILON   1e-12"
.PP
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBMSLMatrix\fP & M)"
.PP
.SS "istream& operator>> (istream & is, \fBMSLMatrix\fP & M)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
