.TH "modelmisc.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modelmisc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'model.h'\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'matrix.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBModel1D\fP"
.br
.RI "\fIA simple one-dimensional model for dynamics studies.\fP"
.ti -1c
.RI "class \fBModelLinear\fP"
.br
.RI "\fIA linear systems model: xdot = Ax + Bu.\fP"
.ti -1c
.RI "class \fBModelND\fP"
.br
.RI "\fISimple axis-parallel motions in an N-dimensional space.\fP"
.ti -1c
.RI "class \fBModelNintegrator\fP"
.br
.RI "\fIThe 'nonholonomic integrator', used by R. Brockett and many others.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
