.TH "model2d.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model2d.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'MSL/model2d.h'\fP
.br
\fC#include 'MSL/defs.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNUM_INPUTS_2DPOINT\fP   50"
.br
.ti -1c
.RI "#define \fBNUM_INPUTS_2DRIGID\fP   8"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define NUM_INPUTS_2DPOINT   50"
.PP
.SS "#define NUM_INPUTS_2DRIGID   8"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
