.TH "modelmisc.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modelmisc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fR
.br
\fC#include "model.h"\fR
.br
\fC#include "vector.h"\fR
.br
\fC#include "matrix.h"\fR
.br
\fC#include "util.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBModel1D\fR"
.br
.RI "\fIA simple one-dimensional model for dynamics studies.\fR"
.ti -1c
.RI "class \fBModelLinear\fR"
.br
.RI "\fIA linear systems model: xdot = Ax + Bu.\fR"
.ti -1c
.RI "class \fBModelND\fR"
.br
.RI "\fISimple axis-parallel motions in an N-dimensional space.\fR"
.ti -1c
.RI "class \fBModelNintegrator\fR"
.br
.RI "\fIThe "nonholonomic integrator", used by R. Brockett and many others.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.