.TH "model3d.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model3d.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector.h>\fR
.br
\fC#include "model.h"\fR
.br
\fC#include "matrix.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBModel3D\fR"
.br
.RI "\fIA base class for all models in 3D worlds.\fR"
.ti -1c
.RI "class \fBModel3DRigid\fR"
.br
.RI "\fIA rigid robot in a 3D world.\fR"
.ti -1c
.RI "class \fBModel3DRigidChain\fR"
.br
.RI "\fIA 3D kinematic chain of bodies that uses DH parameters.\fR"
.ti -1c
.RI "class \fBModel3DRigidMulti\fR"
.br
.RI "\fIA collection of free-floating bodies in a 3D world.\fR"
.ti -1c
.RI "class \fBModel3DRigidTree\fR"
.br
.RI "\fIA 3D kinematic tree of bodies that uses DH parameters.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.