.TH "model3d.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model3d.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'model.h'\fP
.br
\fC#include 'matrix.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBModel3D\fP"
.br
.RI "\fIA base class for all models in 3D worlds.\fP"
.ti -1c
.RI "class \fBModel3DRigid\fP"
.br
.RI "\fIA rigid robot in a 3D world.\fP"
.ti -1c
.RI "class \fBModel3DRigidChain\fP"
.br
.RI "\fIA 3D kinematic chain of bodies that uses DH parameters.\fP"
.ti -1c
.RI "class \fBModel3DRigidMulti\fP"
.br
.RI "\fIA collection of free-floating bodies in a 3D world.\fP"
.ti -1c
.RI "class \fBModel3DRigidTree\fP"
.br
.RI "\fIA 3D kinematic tree of bodies that uses DH parameters.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
