.TH "modelnew.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modelnew.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <MSL/model3d.h>\fP
.br
\fC#include 'modelnew.h'\fP
.br

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
