.TH "Model2DRigidCarForward" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model2DRigidCarForward \- A rigid car-like robot that can only go forward in a 2D world. 
.SH SYNOPSIS
.br
.PP
\fC#include <model2d.h>\fP
.PP
Inherits \fBModel2DRigidCar\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBModel2DRigidCarForward\fP (string path)"
.br
.ti -1c
.RI "virtual \fB~Model2DRigidCarForward\fP ()"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
A rigid car-like robot that can only go forward in a 2D world.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "Model2DRigidCarForward::Model2DRigidCarForward (string path)"
.PP
.SS "virtual Model2DRigidCarForward::~Model2DRigidCarForward ()\fC [inline, virtual]\fP"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
