.TH "model2d.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model2d.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream.h>\fR
.br
\fC#include <math.h>\fR
.br
\fC#include "model2d.h"\fR
.br
\fC#include "defs.h"\fR
.br

.SS Defines

.in +1c
.ti -1c
.RI "#define \fBNUM_INPUTS_2DPOINT\fR  50"
.br
.ti -1c
.RI "#define \fBNUM_INPUTS_2DRIGID\fR  8"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define NUM_INPUTS_2DPOINT  50
.PP
.SS #define NUM_INPUTS_2DRIGID  8
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.