.TH "modelnew.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modelnew.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'MSL/MSL.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBModel3DRigidHelical\fP"
.br
.RI "\fIA rigid robot that moves along helical paths in a 3D world.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
