.TH "model.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list.h>\fR
.br
\fC#include <string>\fR
.br
\fC#include "vector.h"\fR
.br
\fC#include "matrix.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBModel\fR"
.br
.RI "\fIThe incremental simulator model.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.