.TH "model.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'matrix.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBModel\fP"
.br
.RI "\fIThe incremental simulator model.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
