.TH "Model3D" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model3D \- A base class for all models in 3D worlds. 
.SH SYNOPSIS
.br
.PP
\fC#include <model3d.h>\fP
.PP
Inherits \fBModel\fP.
.PP
Inherited by \fBModel3DRigid\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBModel3D\fP (string path)"
.br
.ti -1c
.RI "virtual \fB~Model3D\fP ()"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
A base class for all models in 3D worlds.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "Model3D::Model3D (string path)"
.PP
.SS "virtual Model3D::~Model3D ()\fC [inline, virtual]\fP"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
