.TH "model3ddyn.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model3ddyn.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'renderglobj.h'\fP
.br
\fC#include 'model3d.h'\fP
.br
\fC#include 'matrix.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBModel3DDyn\fP"
.br
.RI "\fIA spacecraft model with three thrusters providing both tranlation force and rotation torque.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
