.TH "ModelCarDynSmoothRollover" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelCarDynSmoothRollover \- One more dimension than \fBModelCarDynRollover\fP considering the steering angle can only change continuously. 
.SH SYNOPSIS
.br
.PP
\fC#include <modelcar.h>\fP
.PP
Inherits \fBModelCarDynRollover\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBModelCarDynSmoothRollover\fP (string path)"
.br
.ti -1c
.RI "virtual \fB~ModelCarDynSmoothRollover\fP ()"
.br
.ti -1c
.RI "virtual \fBMSLVector\fP \fBStateTransitionEquation\fP (const \fBMSLVector\fP &x1, const \fBMSLVector\fP &u)"
.br
.RI "\fIThe state transition equation, or equations of motion, xdot=f(x,u).\fP"
.ti -1c
.RI "virtual \fBMSLVector\fP \fBStateToConfiguration\fP (const \fBMSLVector\fP &\fBx\fP)"
.br
.RI "\fIA method that converts a \fBModel\fP state in to a \fBGeom\fP configuration.\fP"
.ti -1c
.RI "virtual double \fBMetric\fP (const \fBMSLVector\fP &x1, const \fBMSLVector\fP &x2)"
.br
.RI "\fIA distance metric, which is Euclidean in the base class.\fP"
.ti -1c
.RI "virtual \fBMSLVector\fP \fBLinearInterpolate\fP (const \fBMSLVector\fP &x1, const \fBMSLVector\fP &x2, const double &a)"
.br
.RI "\fILinearly interpolate two state while respecting topology.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
One more dimension than \fBModelCarDynRollover\fP considering the steering angle can only change continuously.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "ModelCarDynSmoothRollover::ModelCarDynSmoothRollover (string path)"
.PP
.SS "virtual ModelCarDynSmoothRollover::~ModelCarDynSmoothRollover ()\fC [inline, virtual]\fP"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "\fBMSLVector\fP ModelCarDynSmoothRollover::LinearInterpolate (const \fBMSLVector\fP & x1, const \fBMSLVector\fP & x2, const double & a)\fC [virtual]\fP"
.PP
Linearly interpolate two state while respecting topology.
.PP
If a=0, then x1 is returned; if a=1, then x2 is returned. All intermediate values of $a \\in [0,1]$ yield intermediate states. This method is defined by \fBModel\fP. 
.PP
Reimplemented from \fBModel2DRigidDyncar\fP.
.SS "double ModelCarDynSmoothRollover::Metric (const \fBMSLVector\fP & x1, const \fBMSLVector\fP & x2)\fC [virtual]\fP"
.PP
A distance metric, which is Euclidean in the base class.
.PP
Reimplemented from \fBModelCarDynRollover\fP.
.SS "\fBMSLVector\fP ModelCarDynSmoothRollover::StateToConfiguration (const \fBMSLVector\fP & x)\fC [virtual]\fP"
.PP
A method that converts a \fBModel\fP state in to a \fBGeom\fP configuration.
.PP
Reimplemented from \fBModelCarDynRollover\fP.
.SS "\fBMSLVector\fP ModelCarDynSmoothRollover::StateTransitionEquation (const \fBMSLVector\fP & x1, const \fBMSLVector\fP & u)\fC [virtual]\fP"
.PP
The state transition equation, or equations of motion, xdot=f(x,u).
.PP
Reimplemented from \fBModelCarDynRollover\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
