.TH "msllist.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msllist.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stream.h>\fP
.br
\fC#include <list.h>\fP
.br
\fC#include <vector.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T, class A = allocator<T>> ostream & \fBoperator<<\fP (ostream &out, const list< T > &L)"
.br
.ti -1c
.RI "template<class T, class A = allocator<T>> istream & \fBoperator>>\fP (istream &in, list< T > &L)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "template<class T, class A = allocator<T>> ostream & operator<< (ostream & out, const list< T > & L)"
.PP
.SS "template<class T, class A = allocator<T>> istream & operator>> (istream & in, list< T > & L)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
