.TH "MSLList" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSLList \- 
.SH SYNOPSIS
.br
.PP
\fC#include <msllist.h>\fP
.PP
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const MSLList< T > &L)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &in, MSLList< T > &L)"
.br
.in -1c

.SS "template<class T, class A = allocator<T>> class MSLList< T, A >"

.SH "FRIENDS AND RELATED FUNCTION DOCUMENTATION"
.PP 
.SS "template<class T, class A = allocator<T>> ostream& operator<< (ostream & out, const MSLList< T > & L)\fC [friend]\fP"
.PP
.SS "template<class T, class A = allocator<T>> istream& operator>> (istream & in, MSLList< T > & L)\fC [friend]\fP"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
