.TH "MSLPolygon" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSLPolygon \- 
.SH SYNOPSIS
.br
.PP
\fC#include <polygon.h>\fP
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBMSLPolygon\fP ()"
.br
.ti -1c
.RI "\fB~MSLPolygon\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "list< \fBMSLPoint\fP > \fBLPoints\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &in, MSLPolygon &P)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const MSLPolygon &P)"
.br
.in -1c
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "MSLPolygon::MSLPolygon ()\fC [inline]\fP"
.PP
.SS "MSLPolygon::~MSLPolygon ()\fC [inline]\fP"
.PP
.SH "FRIENDS AND RELATED FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & out, const MSLPolygon & P)\fC [friend]\fP"
.PP
.SS "istream& operator>> (istream & in, MSLPolygon & P)\fC [friend]\fP"
.PP
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "list<\fBMSLPoint\fP> MSLPolygon::LPoints"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
