.TH "nodeinfo.h" 3 "26 Feb 2002" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nodeinfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vector.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLNodeInfo\fP"
.br
.RI "\fIThe information holded in this class is explained in 'Reducing Metric Sensitivity in Randomized Trajectory Design' in IEEE/RSJ International Conference on Intelligent Robots and Systems, 2001.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.