.TH "nogui.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nogui.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list.h>\fR
.br
\fC#include <string>\fR
.br
\fC#include <fstream.h>\fR
.br
\fC#include <MSL/model3d.h>\fR
.br
\fC#include <MSL/geomPQP.h>\fR
.br
\fC#include <MSL/problem.h>\fR
.br
\fC#include <MSL/rrt.h>\fR
.br

.SS Functions

.in +1c
.ti -1c
.RI "\fBmain\fR (int argc, char **argv)"
.br
.RI "\fIA simple test program that runs a planner without a GUI.\fR"
.in -1c
.SH FUNCTION DOCUMENTATION
.PP 
.SS main (int argc, char ** argv)
.PP
A simple test program that runs a planner without a GUI.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.