.TH "point.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include 'MSL/point.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3.1415926535897932385"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBside_of_circle\fP (const \fBMSLPoint\fP &a, const \fBMSLPoint\fP &b, const \fBMSLPoint\fP &c, const \fBMSLPoint\fP &d)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const \fBMSLPoint\fP &p)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &in, \fBMSLPoint\fP &p)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define PI   3.1415926535897932385"
.PP
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & out, const \fBMSLPoint\fP & p)"
.PP
.SS "istream& operator>> (istream & in, \fBMSLPoint\fP & p)"
.PP
.SS "int side_of_circle (const \fBMSLPoint\fP & a, const \fBMSLPoint\fP & b, const \fBMSLPoint\fP & c, const \fBMSLPoint\fP & d)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
