.TH "point3d.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point3d.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fR
.br
\fC#include <ctype.h>\fR
.br
\fC#include "point3d.h"\fR
.br

.SS Functions

.in +1c
.ti -1c
.RI "ostream& \fBoperator<<\fR (ostream &out, const list< \fBMSLPoint3d\fR > &L)"
.br
.ti -1c
.RI "istream& \fBoperator>>\fR (istream &in, list< \fBMSLPoint3d\fR > &L)"
.br
.ti -1c
.RI "ostream& \fBoperator<<\fR (ostream &out, const \fBMSLPoint3d\fR &p)"
.br
.ti -1c
.RI "istream& \fBoperator>>\fR (istream &in, \fBMSLPoint3d\fR &p)"
.br
.in -1c
.SH FUNCTION DOCUMENTATION
.PP 
.SS ostream& operator<< (ostream & out, const \fBMSLPoint3d\fR & p)
.PP
.SS ostream& operator<< (ostream & out, const list< \fBMSLPoint3d\fR > & L)
.PP
.SS istream& operator>> (istream & in, \fBMSLPoint3d\fR & p)
.PP
.SS istream& operator>> (istream & in, list< \fBMSLPoint3d\fR > & L)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.