.TH "point3d.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point3d.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include 'MSL/point3d.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const \fBMSLPoint3d\fP &p)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &in, \fBMSLPoint3d\fP &p)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "ostream& operator<< (ostream & out, const \fBMSLPoint3d\fP & p)"
.PP
.SS "istream& operator>> (istream & in, \fBMSLPoint3d\fP & p)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
