.TH "prm.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include 'planner.h'\fP
.br
\fC#include 'util.h'\fP
.br
\fC#include 'disjointsets.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBPRM\fP"
.br
.RI "\fIA probabilistic roadmap planner, proposed by Kavraki, Svestka, Latombe, Overmars, 1994.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
