.TH "problem.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
problem.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'model.h'\fP
.br
\fC#include 'geom.h'\fP
.br
\fC#include 'util.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBProblem\fP"
.br
.RI "\fIAn interface class that provides the primary input to a planner.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
