.TH "problem.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
problem.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list.h>\fR
.br
\fC#include <string>\fR
.br
\fC#include "model.h"\fR
.br
\fC#include "geom.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBProblem\fR"
.br
.RI "\fIAn interface class that provides the primary input to a planner.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.