.TH "random.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include "random.h"\fR
.br
\fC#include <time.h>\fR
.br

.SS Defines

.in +1c
.ti -1c
.RI "#define \fBRANDMAX\fR  0x7FFFFFFF"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define RANDMAX  0x7FFFFFFF
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.