.TH "random.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MSL/random.h'\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
