.TH "rcrrt.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rcrrt.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'MSL/vector.h'\fP
.br
\fC#include 'MSL/rrt.h'\fP
.br
\fC#include 'MSL/rcrrtnodeinfo.h'\fP
.br
\fC#include 'MSL/rcrrt.h'\fP
.br
\fC#include 'MSL/defs.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBACKTREE_ANALYSIS\fP   1"
.br
.ti -1c
.RI "#define \fBFOREWARDTREE_ANALYSIS\fP   2"
.br
.ti -1c
.RI "#define \fBNON_ANALYSIS\fP   0"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define BACKTREE_ANALYSIS   1"
.PP
.SS "#define FOREWARDTREE_ANALYSIS   2"
.PP
.SS "#define NON_ANALYSIS   0"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
