.TH "rendergl.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rendergl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glut.h>\fR
.br
\fC#include <GL/gl.h>\fR
.br
\fC#include <vector.h>\fR
.br
\fC#include <string>\fR
.br
\fC#include "triangle.h"\fR
.br
\fC#include "render.h"\fR
.br
\fC#include "renderglobj.h"\fR
.br
\fC#include "defs.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBRenderGL\fR"
.br
.RI "\fIPerform 3D rendering using the GL and GLUT libraries.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.