.TH "rendergl.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rendergl.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'MSL/rendergl.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRenderGL\fP * \fBRGL\fP"
.br
.in -1c
.SH "VARIABLE DOCUMENTATION"
.PP 
.SS "\fBRenderGL\fP* RGL"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
