.TH "renderiv.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderiv.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'triangle.h'\fP
.br
\fC#include 'render.h'\fP
.br
\fC#include 'point.h'\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'renderglobj.h'\fP
.br
\fC#include <Xm/Xm.h>\fP
.br
\fC#include <Inventor/Xt/SoXt.h>\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRenderIv\fP"
.br
.RI "\fIPerform 3D rendering using the OpenInventor library.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
