.TH "renderiv.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderiv.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fR
.br
\fC#include <stdlib.h>\fR
.br
\fC#include <assert.h>\fR
.br
\fC#include <Xm/Xm.h>\fR
.br
\fC#include <Inventor/Xt/SoXt.h>\fR
.br
\fC#include <Inventor/SoDB.h>\fR
.br
\fC#include <Inventor/Xt/viewers/SoXtExaminerViewer.h>\fR
.br
\fC#include <Inventor/nodes/SoTransform.h>\fR
.br
\fC#include <Inventor/nodes/SoSeparator.h>\fR
.br
\fC#include <Inventor/nodes/SoCamera.h>\fR
.br
\fC#include <Inventor/nodes/SoIndexedFaceSet.h>\fR
.br
\fC#include <Inventor/nodes/SoMaterial.h>\fR
.br
\fC#include <Inventor/nodes/SoLineSet.h>\fR
.br
\fC#include <Inventor/nodes/SoSwitch.h>\fR
.br
\fC#include <Inventor/sensors/SoTimerSensor.h>\fR
.br
\fC#include <Inventor/fields/SoMFInt32.h>\fR
.br
\fC#include "renderiv.h"\fR
.br
\fC#include "defs.h"\fR
.br

.SS Variables

.in +1c
.ti -1c
.RI "const short \fBDEF_VIEWER_WIDTH\fR = 500"
.br
.ti -1c
.RI "const short \fBDEF_VIEWER_HEIGHT\fR = 400"
.br
.in -1c
.SH VARIABLE DOCUMENTATION
.PP 
.SS const short DEF_VIEWER_HEIGHT = 400
.PP
.SS const short DEF_VIEWER_WIDTH = 500
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.