.TH "render.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
render.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'scene.h'\fP
.br
\fC#include 'gui.h'\fP
.br
\fC#include 'mslio.h'\fP
.br
\fC#include 'util.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRender\fP"
.br
.RI "\fIA rendering class that accepts commands from a \fBGui\fP, and determines using specific graphics libraries how to draw the results on a screen.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRENDERCOLORS\fP   10"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define RENDERCOLORS   10"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
