.TH "renderiv.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderiv.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include <Xm/Xm.h>\fP
.br
\fC#include <Xm/Form.h>\fP
.br
\fC#include <Inventor/Xt/SoXt.h>\fP
.br
\fC#include <Inventor/SoDB.h>\fP
.br
\fC#include <Inventor/Xt/viewers/SoXtExaminerViewer.h>\fP
.br
\fC#include <Inventor/nodes/SoTransform.h>\fP
.br
\fC#include <Inventor/nodes/SoSeparator.h>\fP
.br
\fC#include <Inventor/nodes/SoCamera.h>\fP
.br
\fC#include <Inventor/nodes/SoIndexedFaceSet.h>\fP
.br
\fC#include <Inventor/nodes/SoMaterial.h>\fP
.br
\fC#include <Inventor/nodes/SoLineSet.h>\fP
.br
\fC#include <Inventor/nodes/SoSwitch.h>\fP
.br
\fC#include <Inventor/sensors/SoTimerSensor.h>\fP
.br
\fC#include <Inventor/fields/SoMFInt32.h>\fP
.br
\fC#include <Inventor/nodes/SoPerspectiveCamera.h>\fP
.br
\fC#include <Inventor/nodes/SoDirectionalLight.h>\fP
.br
\fC#include <Inventor/nodes/SoPointLight.h>\fP
.br
\fC#include <Inventor/nodes/SoOrthographicCamera.h>\fP
.br
\fC#include <Inventor/nodes/SoRotationXYZ.h>\fP
.br
\fC#include <Inventor/nodes/SoScale.h>\fP
.br
\fC#include <Inventor/nodes/SoTranslation.h>\fP
.br
\fC#include <Inventor/nodes/SoRotation.h>\fP
.br
\fC#include <Inventor/fields/SoSFVec3f.h>\fP
.br
\fC#include 'MSL/renderiv.h'\fP
.br
\fC#include 'MSL/defs.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const short \fBDEF_VIEWER_WIDTH\fP = 500"
.br
.ti -1c
.RI "const short \fBDEF_VIEWER_HEIGHT\fP = 400"
.br
.ti -1c
.RI "const short \fBMULTIPLE_VIEWER_WIDTH\fP = 450"
.br
.ti -1c
.RI "const short \fBMULTIPLE_VIEWER_HEIGHT\fP = 350"
.br
.ti -1c
.RI "\fBRenderIv\fP * \fBRIV\fP"
.br
.in -1c
.SH "VARIABLE DOCUMENTATION"
.PP 
.SS "const short DEF_VIEWER_HEIGHT = 400"
.PP
.SS "const short DEF_VIEWER_WIDTH = 500"
.PP
.SS "const short MULTIPLE_VIEWER_HEIGHT = 350"
.PP
.SS "const short MULTIPLE_VIEWER_WIDTH = 450"
.PP
.SS "\fBRenderIv\fP* RIV"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
