.TH "render.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
render.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fR
.br
\fC#include <stdio.h>\fR
.br
\fC#include <string.h>\fR
.br
\fC#include "scene.h"\fR
.br
\fC#include "gui.h"\fR
.br
\fC#include "util.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBRender\fR"
.br
.RI "\fIA rendering class that accepts commands from a \fBGui\fR, and determines using specific graphics libraries how to draw the results on a screen.\fR"
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBRENDERCOLORS\fR  10"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define RENDERCOLORS  10
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.