.TH "render.C" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
render.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fR
.br
\fC#include <stdlib.h>\fR
.br
\fC#include "render.h"\fR
.br
\fC#include "defs.h"\fR
.br
\fC#include "pixmaps/ff.xpm"\fR
.br
\fC#include "pixmaps/pause.xpm"\fR
.br
\fC#include "pixmaps/play.xpm"\fR
.br
\fC#include "pixmaps/rw.xpm"\fR
.br
\fC#include "pixmaps/stop.xpm"\fR
.br
\fC#include "pixmaps/prev.xpm"\fR
.br
\fC#include "pixmaps/next.xpm"\fR
.br
\fC#include "pixmaps/msl.xpm"\fR
.br

.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.