.TH "renderpf.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderpf.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'MSL/renderpf.h'\fP
.br
\fC#include 'MSL/defs.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCONTROLPANEL_CENTER_X\fP   -0.22"
.br
.ti -1c
.RI "#define \fBCONTROLPANEL_CENTER_Z\fP   -0.37"
.br
.ti -1c
.RI "#define \fBCONTROLPANEL_WIDTH\fP   0.2"
.br
.ti -1c
.RI "#define \fBCONTROLPANEL_HEIGHT\fP   0.1"
.br
.ti -1c
.RI "#define \fBCONTROLPANEL_BAR_WIDTH\fP   0.18"
.br
.ti -1c
.RI "#define \fBCONTROLPANEL_BAR_HEIGHT\fP   0.005"
.br
.ti -1c
.RI "#define \fBCONTROLPAD_WIDTH\fP   0.01"
.br
.ti -1c
.RI "#define \fBCONTROLPAD_HEIGHT\fP   0.02"
.br
.ti -1c
.RI "#define \fBANIMATING_SPEED_FACTOR\fP   10"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define ANIMATING_SPEED_FACTOR   10"
.PP
.SS "#define CONTROLPAD_HEIGHT   0.02"
.PP
.SS "#define CONTROLPAD_WIDTH   0.01"
.PP
.SS "#define CONTROLPANEL_BAR_HEIGHT   0.005"
.PP
.SS "#define CONTROLPANEL_BAR_WIDTH   0.18"
.PP
.SS "#define CONTROLPANEL_CENTER_X   -0.22"
.PP
.SS "#define CONTROLPANEL_CENTER_Z   -0.37"
.PP
.SS "#define CONTROLPANEL_HEIGHT   0.1"
.PP
.SS "#define CONTROLPANEL_WIDTH   0.2"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
