.TH "rendergl.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rendergl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../../configs/configGLUT.h'\fP
.br
\fC#include '../../configs/configGL.h'\fP
.br
\fC#include 'render.h'\fP
.br
\fC#include 'triangle.h'\fP
.br
\fC#include 'renderglobj.h'\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'defs.h'\fP
.br
\fC#include 'util.h'\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRenderGL\fP"
.br
.RI "\fIPerform 3D rendering using the GL and GLUT libraries.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
