.TH "render.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
render.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'MSL/render.h'\fP
.br
\fC#include 'MSL/defs.h'\fP
.br
\fC#include 'pixmaps/ff.xpm'\fP
.br
\fC#include 'pixmaps/pause.xpm'\fP
.br
\fC#include 'pixmaps/play.xpm'\fP
.br
\fC#include 'pixmaps/rw.xpm'\fP
.br
\fC#include 'pixmaps/stop.xpm'\fP
.br
\fC#include 'pixmaps/prev.xpm'\fP
.br
\fC#include 'pixmaps/next.xpm'\fP
.br
\fC#include 'pixmaps/msl.xpm'\fP
.br

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
