.TH "renderpf.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderpf.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "triangle.h"\fR
.br
\fC#include "render.h"\fR
.br
\fC#include <Performer/pf/pfChannel.h>\fR
.br
\fC#include <Performer/pf/pfEarthSky.h>\fR
.br
\fC#include <Performer/pf/pfLightSource.h>\fR
.br
\fC#include <Performer/pf/pfNode.h>\fR
.br
\fC#include <Performer/pf/pfGeode.h>\fR
.br
\fC#include <Performer/pf/pfText.h>\fR
.br
\fC#include <Performer/pf/pfScene.h>\fR
.br
\fC#include <Performer/pf/pfGroup.h>\fR
.br
\fC#include <Performer/pf/pfSwitch.h>\fR
.br
\fC#include <Performer/pf/pfDCS.h>\fR
.br
\fC#include <Performer/pf/pfSCS.h>\fR
.br
\fC#include <Performer/pr/pfGeoSet.h>\fR
.br
\fC#include <Performer/pr/pfGeoState.h>\fR
.br
\fC#include <Performer/pr/pfString.h>\fR
.br
\fC#include <Performer/pr/pfFont.h>\fR
.br
\fC#include <Performer/pr/pfMaterial.h>\fR
.br
\fC#include <Performer/pfui.h>\fR
.br
\fC#include <Performer/pfutil.h>\fR
.br
\fC#include <Performer/pfdu.h>\fR
.br
\fC#include <Performer/pr.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBRenderPerformer\fR"
.br
.RI "\fIPerform 3D rendering using the SGI IRIS Performer library.\fR"
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.