.TH "rrtslide.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rrtslide.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <MSL/vector.h>\fP
.br
\fC#include <MSL/tree.h>\fP
.br
\fC#include <MSL/rrt.h>\fP
.br
\fC#include <MSL/defs.h>\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRRTSlide\fP"
.br
.RI "\fIIn the Connect method, slide along the walls.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
