.TH "setup.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup.h \- 
.SH SYNOPSIS
.br
.PP
.SS Functions

.in +1c
.ti -1c
.RI "void \fBSetupProblem\fR (\fBModel\fR *&m, \fBGeom\fR *&g, string path)"
.br
.in -1c
.SH FUNCTION DOCUMENTATION
.PP 
.SS void SetupProblem (\fBModel\fR *& m, \fBGeom\fR *& g, string path)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.