.TH "solver.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'problem.h'\fP
.br
\fC#include 'util.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBSolver\fP"
.br
.RI "\fIThe base class for all path planners.\fP"
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
