.TH "tree.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLNode\fP"
.br
.ti -1c
.RI "class \fBMSLNodeGreater\fP"
.br
.RI "\fIThis is a comparison object to be used for STL-based sorting.\fP"
.ti -1c
.RI "class \fBMSLNodeLess\fP"
.br
.RI "\fIThis is a comparison object to be used for STL-based sorting.\fP"
.ti -1c
.RI "class \fBMSLTree\fP"
.br
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
