.TH "util.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <dirent.h>\fP
.br
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBused_time\fP ()"
.br
.ti -1c
.RI "float \fBused_time\fP (float &)"
.br
.ti -1c
.RI "bool \fBis_file\fP (string fname)"
.br
.ti -1c
.RI "bool \fBis_directory\fP (string fname)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "bool is_directory (string fname)"
.PP
.SS "bool is_file (string fname)"
.PP
.SS "float used_time (float &)"
.PP
.SS "float used_time ()"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
