.TH "vector.C" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include 'MSL/vector.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBnil\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &O, const \fBMSLVector\fP &v)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &I, \fBMSLVector\fP &v)"
.br
.ti -1c
.RI "void \fBerror_handler\fP (int i, const char *s)"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define nil   0"
.PP
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "void error_handler (int i, const char * s)"
.PP
.SS "ostream& operator<< (ostream & O, const \fBMSLVector\fP & v)"
.PP
.SS "istream& operator>> (istream & I, \fBMSLVector\fP & v)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
