.TH "vector.h" 3 "8 Nov 2001" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stream.h>\fR
.br
\fC#include <list.h>\fR
.br
\fC#include <vector.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBMSLVector\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "void \fBerror_handler\fR (int i, const char *s)"
.br
.in -1c
.SH FUNCTION DOCUMENTATION
.PP 
.SS void error_handler (int i, const char * s)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.