.TH "vector.h" 3 "24 Jul 2003" "Motion Strategy Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'mslio.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMSLVector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerror_handler\fP (int i, const char *s)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &O, const \fBMSLVector\fP &v)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &I, \fBMSLVector\fP &v)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "void error_handler (int i, const char * s)"
.PP
.SS "ostream& operator<< (ostream & O, const \fBMSLVector\fP & v)"
.PP
.SS "istream& operator>> (istream & I, \fBMSLVector\fP & v)"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for Motion Strategy Library from the source code.
