################################################################
#
# This is the configurable part of the Makefile.
# It must be named 'Makefile.config'.
#
#
################################################################

################
#
# For each conditional install option, either fill in "yes" or leave 
# blank to indicate no.

# Do you want to use the GL-based renderer?
export RENDER_GL = yes

# Do you want to use the Performer-based renderer?
export RENDER_PF =


# Do you want to use the OpenInventor-based renderer?
export RENDER_IV =


################
#
# Define the OS to compile for and the compiler to use.

OS = Linux

# C++ = g++
C++ = em++

################
#
# Define the C++ compiler flags

C++FLAGS = -g -Wall
LDFLAGS = 
CPPFLAGS = 


######### FOX Configuration
#FOXINC = @FOX_INC_F@
#FOXLIB = @FOX_LIB_F@ @PNG_LIB_F@ @JPEG_LIB_F@ -lFOX -ljpeg -lpng
FOXLIB = -lFOX -ljpeg -lpng
FOXFLAGS = -DTIME_WITH_SYS_TIME=1 -DHAVE_UNISTD_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_ZLIB_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_PNG_H=1 -DHAVE_OPENGL -DHAVE_JPEG

#########  PQP Configuration
#PQPINC = @INCPQP@
#PQPLIB = @LDPQP@ -lPQP
PQPLIB = -lPQP
PQPFLAGS = -L../PQP_v1.3/lib/ -I../PQP_v1.3/include/

######### X11 Configuration
XINC=-I/usr/X11R6/include
XLIB=-L/usr/X11R6/lib -lX11 -lXmu -lXext -lXi

########   GL Configuration
#GLINC = @GL_INC_F@  @GLUT_INC_F@
#GLLIB = @GL_LIB_F@ @GLUT_LIB_F@ -lglut -lGLU -lGL 
GLLIB = 
GLFLAGS = 

########   Performer Configuration
#PFINC = @PF_INC_F@
#PFLIB = @PF_LIB_F@ -lpfdu -lpfui -lpfuiD -lpfutil -lpf -ldl
PFLIB = -lpfdu -lpfui -lpfuiD -lpfutil -lpf -ldl
PFFLAGS = -g

########   OpenInventor Configuration
#IVINC = @IV_INC_F@
#IVLIB = @IV_LIB_F@  -lInventor -lInventorXt -lXm -lGLU -lGL -ldl -lXaw
IVLIB = -lInventor -lInventorXt -lXm -lGLU -lGL -ldl -lXaw
IVFLAGS = -DPOSIX_SOURCE -D_XOPEN_SOURCE

######### Others
OTHERINC = -I../include
OTHERLIB = -L../lib